# Generated by Django 4.2.5 on 2023-10-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_installation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('Working', 'Working'), ('Failing', 'Failing')], default='Working', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='username',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
