# Generated by Django 4.2.5 on 2023-10-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_location_phone_number_location_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='location',
            name='username',
        ),
    ]
