Name: Django CI/CD

on:
  push:
    branches: [ "main" ]
    branches: [ "staging" ]
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]
    branches: [ "staging" ]
    branches: [ "dev" ]
  
jobs:
  build:

    runs-on: ubuntu-20.04
    - name : python-version
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python3 manage.py test
      makemigrations:
        python3 manage.py migrate
      runserver:
        python3 manage.py runserver
    - name: Format Code with pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files
